name: Deploy Flask App to EC2

on:
  workflow_dispatch:  # Manual trigger from GitHub GUI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image locally on the GitHub runner
      - name: Build Docker Image
        run: docker build -t flask-app:latest .

      # 4️⃣ SSH into EC2 and deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Stop and remove existing container if it exists
            docker stop flask-app || true
            docker rm flask-app || true
            
            # Copy Docker image from GitHub runner to EC2
            docker save flask-app:latest | bzip2 | ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bunzip2 | docker load'
            
            # Run the container
            docker run -d -p 5000:5000 --name flask-app flask-app:latest
