name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

    - name: Push Image
      run: |
        docker tag flask-app ${{ secrets.DOCKERHUB_USER }}/flask-app:latest
        docker push ${{ secrets.DOCKERHUB_USER }}/flask-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/flask-app:latest
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 5000:5000 --name flask-app ${{ secrets.DOCKERHUB_USER }}/flask-app:latest
